baseURL = 'https://manfai.me/'
defaultContentLang = 'en'
[languages]
  [languages.en]
    title = 'manfai.me'
    weight = 1
  [languages.zh-hk]
    title = '文輝的網站'
    author = '文永輝'
    weight = 2
  [languages.zh-cn]
    title = '文辉的网站'
    author = '文永辉'
    weight = 3
[params]
  githubUsername = 'manfai106'
  author = 'Man Wing Fai'
  linkedinUsername = 'manfai106' 
  twitterUsername = 'manfai106'
  introduction  = ''
  phone = ''
  email = ''
  address = ''
  residence = ''
  [params.navigation]
    help = 'Help'
[[module.mounts]]
  source = 'assets'
  target = 'assets'
